### ISSUE TITLE
Attack Pattern ID prefix 'C' conflicts with Mitre Att&ck Campaign ID

### ISSUE THREAD

**Issue by mmulich** [MBCProject/mbc-stix2#15]
The 12.x releases of the Mitre Attack data have a new Campaign type that uses the `C####` identifier scheme. This conflicts with the same pre-existing Attack Pattern identifier scheme in MBC data.

For example, Attack Pattern "HTTP Communication" with ID `C0002` now conflicts with [Campaign "Night Dragon"](https://attack.mitre.org/campaigns/C0002/).

Is there any plan to address or resolve this ID conflict?

**Comment by dzbeck** [comment]
@mmulich thanks for your comment. The MBC team has been in contact with the ATT&CK team and unfortunately, there doesn't seem anyway to resolve the conflict. MBC micro-behaviors are actively being used, as are ATT&CK Campaigns. To change either would be a break change for too many users. We're hoping that micro-behaviors and campaigns being very different things, not used in the same context, will make the conflict less of an issue. And going forward, we'll work harder to make sure similar conflicts are avoided. Sorry not to have a better answer.
