### ISSUE TITLE
Integration with attack-navigator and attack 10.1 fails with invalid format error

### ISSUE THREAD

**Issue by watgh** [MBCProject/mbc-stix2#6]
With the new release of ATT&CK we've updated our standalone instance using the attack-nav-mod.py script which worked with ATT&CK v9.0.  When attempting to use an MBC layer, navigator complains with:

Error: external_references has inavaid format in imported BaseStix object (ID: x-mitre-tactic--eb6166b0-f3c9-4124-aeb9-662941baa19e

javascript stack trace:

at new BaseStix (main-es2018.js:5072)
at new Tactic (main-es2018.js:5163)
at main-es2018.js:5150
at Array.map (<anonymous>)
at new Matrix (main-es2018.js:5150)
at DataService.parseBundle (main-es2018.js:4836)
at Object.next (main-es2018.js:4944)
at SafeSubscriber.__tryOrUnsub (vendor-es2018.js:22389)
at SafeSubscriber.next (vendor-es2018.js:22326)
at Subscriber._next (vendor-es2018.js:22276)
defaultErrorLogger @ core.js:6006

**Comment by watgh** [comment]
UPDATE:  The ordering of external references not matters with Navigator now enforcing its ATT&CK model.  The FIRST external reference must contain the external ID.  
Related Navigator ticket:  https://github.com/mitre-attack/attack-navigator/issues/362

If possible, it would be helpful for the mbc stix to match this [ABSURD!] requirement, even though I think navigator should write their code better.

**Comment by emmanvg** [comment]
@watgh thanks for raising this issue!

In release v22.02 of the MBC content, I looked into the ordering problem on the `x-mitre-tactic objects` and corrected this error.
