### ISSUE TITLE
Update of MBC STIX to mbc-markdown version

### ISSUE THREAD

**Issue by kn0wl3dge** [MBCProject/mbc-stix2#7]
MBC has evolved a lot the past few months through the [mbc-markdown](https://github.com/MBCProject/mbc-markdown) repository. Many new rules have been added.
However, the MBC STIX version is not up to date with the markdown repository.
The STIX version of MBC is really useful for programming related task.

Do you plan to update this repository any day soon?

**Comment by emmanvg** [comment]
Hi @kn0wl3dge thanks for raising this issue. Just wanted to let you know that we are working on releasing a new version of MBCProject/mbc-stix2 to align this data with the latest from the markdown content. It should be out soon.

**Comment by kn0wl3dge** [comment]
Hi @emmanvg, 
That's an awesome news. I will be glad to give a hand if you need it.

**Comment by emmanvg** [comment]
A new release of the MBC content has been made (v2.2) in order to version control the changes from `mbc-markdown`.
I updated `mbc-stix2` accordingly to match the latest content! 🥂
